### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by alienzj** [Zymo-Research/figaro#61]
```
figaro.py --help
Traceback (most recent call last):
  File "/home/jiezhu/.conda/envs/bioenv3.12/bin/figaro.py", line 4, in <module>
    import figaroSupport
ModuleNotFoundError: No module named 'figaroSupport'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiezhu/.conda/envs/bioenv3.12/bin/figaro.py", line 6, in <module>
    from . import figaroSupport
ImportError: attempted relative import with no known parent package
```

**Comment by alienzj** [comment]
Installation:
```
mamba install -c bioconda figaro
```

**Comment by alienzj** [comment]
And install by commondline:
```
python figaro.py --help                                                                                                                                                       (bioenv3.12)
Traceback (most recent call last):
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/figaro.py", line 4, in <module>
    from . import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/trimParameterPrediction.py", line 4, in <module>
    from . import fileNamingStandards
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/figaro.py", line 6, in <module>
    import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/trimParameterPrediction.py", line 9, in <module>
    import fileNamingStandards, fastqHandler, fastqAnalysis, expectedErrorCurve
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/expectedErrorCurve.py", line 13, in <module>
    class ExponentialFit(object):
  File "/mnt/data2/jiezhu/toolkit/figaro/figaro/expectedErrorCurve.py", line 17, in ExponentialFit
    def __init__(self, a:float, b:float, c:float, covariance:collections.Iterable = None, rSquared:float = None, curvePNG:str=None):
                                                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by alienzj** [comment]
Fixed. https://github.com/Zymo-Research/figaro/pull/62

**Comment by ARW-UBT** [comment]
Hello, 
I still experience this issue with figaro v1.1.2. 

```
Traceback (most recent call last):
  File "/home/bt140047/miniconda3/envs/figaro/bin/figaro.py", line 4, in <module>
    import figaroSupport
ModuleNotFoundError: No module named 'figaroSupport'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bt140047/miniconda3/envs/figaro/bin/figaro.py", line 6, in <module>
    from . import figaroSupport
ImportError: attempted relative import with no known parent package
```

Any suggestion how to solve it?
Best regards
